---
- name: Deploy Dotfiles & Shell Profiles
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Deploy /etc/profile
      copy:
        src: Files/profile
        dest: /etc/profile
        owner: root
        group: root
        mode: '0644'

    - name: Deploy /etc/skel/.bash_profile
      copy:
        src: Files/bash_profile
        dest: /etc/skel/.bash_profile
        owner: root
        group: root
        mode: '0644'

    - name: Deploy /etc/profile.d/umask.sh
      copy:
        src: Files/umask.sh
        dest: /etc/profile.d/umask.sh
        owner: root
        group: root
        mode: '0644'

    - name: Deploy /etc/profile.d/rez.sh
      copy:
        src: Files/rez.sh
        dest: /etc/profile.d/rez.sh
        owner: root
        group: root
        mode: '0644'
