---
- name: Install Desktop Environment
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install KDE Plasma Workspaces
      dnf:
        name:
          - '@KDE Plasma Workspaces'
          - '@base-x'
        state: present

    - name: Set graphical target as default
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
        force: true
