---
- name: Join AD Domain
  hosts: localhost
  connection: local
  become: true
  vars:
    realm_name: "alongsidegroup.com"
    realm_user: "{{ lookup('env', 'REALM_USER') | default('Administrator', true) }}"
    realm_workgroup: "ALONGSIDE"
    join_sssd: true
    enable_mkhomedir: true
    realm_password: "{{ lookup('env', 'REALM_PASSWORD') }}"

  tasks:
    - name: Check REALM_PASSWORD is set
      ansible.builtin.assert:
        that:
          - realm_password is defined and realm_password | length > 0
        fail_msg: "REALM_PASSWORD environment variable must be set before running this playbook."
      no_log: yes

    - name: Join AD domain
      community.general.realm:
        name: "{{ realm_name }}"
        user: "{{ realm_user }}"
        password: "{{ realm_password }}"
        state: present
        assume_positive: yes
        assume_resolve: yes
        workgroup: "{{ realm_workgroup }}"
      no_log: yes

    - name: Ensure SSSD is enabled and started
      ansible.builtin.service:
        name: sssd
        enabled: yes
        state: started

    - name: Ensure oddjobd is enabled and started
      ansible.builtin.service:
        name: oddjobd
        enabled: yes
        state: started

    - name: Ensure oddjob-mkhomedir service is enabled
      ansible.builtin.service:
        name: oddjob-mkhomedir
        enabled: yes
