---
- name: Configure SSSD LDAP Settings
  hosts: localhost
  connection: local
  become: true
  vars:
    realm_name: "alongsidegroup.com"

  tasks:
    - name: Ensure SSSD is running
      ansible.builtin.service:
        name: sssd
        enabled: yes
        state: started

    - name: Set fallback_homedir
      ansible.builtin.ini_file:
        path: /etc/sssd/sssd.conf
        section: "domain/{{ realm_name }}"
        option: fallback_homedir
        value: /home/%u
      notify: restart sssd

    - name: Set use_fully_qualified_names
      ansible.builtin.ini_file:
        path: /etc/sssd/sssd.conf
        section: "domain/{{ realm_name }}"
        option: use_fully_qualified_names
        value: "False"
      notify: restart sssd

    - name: Set ldap_idmap_range_min
      ansible.builtin.ini_file:
        path: /etc/sssd/sssd.conf
        section: "domain/{{ realm_name }}"
        option: ldap_idmap_range_min
        value: "1260388352"
      notify: restart sssd

    - name: Set ldap_idmap_default_domain_sid
      ansible.builtin.ini_file:
        path: /etc/sssd/sssd.conf
        section: "domain/{{ realm_name }}"
        option: ldap_idmap_default_domain_sid
        value: "S-1-5-21-2080557663-2646592229-2320375442"
      notify: restart sssd

  handlers:
    - name: restart sssd
      ansible.builtin.service:
        name: sssd
        state: restarted