---
- name: Configure SSSD LDAP Settings
  hosts: localhost
  connection: local
  become: true
  vars:
    realm_name: "alongsidegroup.com"

  tasks:
    - name: Ensure SSSD is running
      ansible.builtin.service:
        name: sssd
        enabled: yes
        state: started

    - name: Set fallback_homedir
      ansible.builtin.lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^fallback_homedir'
        line: 'fallback_homedir = /home/%u'
        insertbefore: '^ldap_id_mapping'
        section: '^\[domain/{{ realm_name }}\]$'

      notify: restart sssd

    - name: Set use_fully_qualified_names
      ansible.builtin.lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^use_fully_qualified_names'
        line: 'use_fully_qualified_names = False'
        insertbefore: '^ldap_id_mapping'
        section: '^\[domain/{{ realm_name }}\]$'

      notify: restart sssd

    - name: Set ldap_idmap_range_min
      ansible.builtin.lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^ldap_idmap_range_min'
        line: 'ldap_idmap_range_min = 1260388352'
        insertbefore: '^ldap_id_mapping'
        section: '^\[domain/{{ realm_name }}\]$'

      notify: restart sssd

    - name: Set ldap_idmap_default_domain_sid
      ansible.builtin.lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^ldap_idmap_default_domain_sid'
        line: 'ldap_idmap_default_domain_sid = S-1-5-21-2080557663-2646592229-2320375442'
        insertbefore: '^ldap_id_mapping'
        section: '^\[domain/{{ realm_name }}\]$'

      notify: restart sssd

  handlers:
    - name: restart sssd
      ansible.builtin.service:
        name: sssd
        state: restarted