---
- name: Setup Machines
  hosts: localhost
  connection: local
  become: true
  
  tasks:

  #UPGRADE
  #------------
  - name: Upgrade all packages
     ansible.builtin.dnf:
      name: "*"
      state: latest
  
  #INSTALL REPO
  #------------
  - name: install Elrepo
    dnf:
     name: elrepo-release
    state: present

  - name: Enable CRB repository
     become: true
     command:
      cmd: dnf config-manager --enable crb
  
  - name: Enable the RPM Fusion repository
     ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
      disable_gpg_check: true
     loop:
      - https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
     become: true

    - name: Add flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        state: present
        method: user

  #DOT FILES
  #------------
  - name: setup DNS
    copy:
     src: Files/resolv.conf
     dest: /etc/resolv.conf
     owner: root
     group: root

  #PROGRAM DEPENDENCIES
  #------------
  - name: install houdini dependencies
    yum:
     name:
      - alsa-lib
      - cups-libs
      - dbus-libs
      - expat
      - fontconfig
      - glib2
      - glibc
      - libcurl
      - libdrm
      - libgcc
      - libglvnd-egl
      - libglvnd-glx
      - libglvnd-opengl
      - libICE
      - libSM
      - libstdc++
      - libuuid
      - libX11
      - libX11-xcb
      - libxcb
      - libXcomposite
      - libXdamage
      - libXext
      - libXfixes
      - libXi
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbfile
      - libXrandr
      - libXrender
      - libxshmfence
      - libXt
      - libXtst
      - mesa-libGLU
      - ncurses-libs
      - nspr
      - nss
      - nss-util
      - nxagent
      - pciutils-libs
      - xcb-util-cursor
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
      - xcb-util-wm
     state: present
     
  - name: Install Cockpit & Dependencies
    yum:
     name:
      - cockpit
      - cockpit-storaged
      - cockpit-shell
      - samba-common-tools
      - adcli
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - krb5-workstation
     state: present
  
  - name: Enable Cockpit on launch
    ansible.builtin.service:
     name: cockpit
     enabled: yes
     state: started
