---
- name: Setup Machines
  hosts: localhost
  connection: local
  become: true
  
  tasks:  
  #DOT FILES
  #------------
  - name: ENV Variables
    copy:
     src: Files/profile
     dest: /etc/profile
     owner: root
     group: root

  #REPO/KERNEL
  #------------
  - name: Ensure the crb repository is enabled
    community.general.dnf_config_manager:
     name: powertools
     state: enabled

  - name: Ensure the epel repository is enabled
    community.general.dnf_config_manager:
     name: epel
     state: enabled

  - name: Elrepo
    dnf:
     name: 'https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm'
     state: present

  - name: install Kernel-ml
    dnf:
     enablerepo: elrepo-kernel
     name:
      - kernel-ml
      - kernel-ml-devel

  - name: Nvida Repo
    ansible.builtin.yum_repository:
     name: cuda-rhel8-x86_64
     description: cuda-rhel8-x86_64
     file: cuda-rhel8
     baseurl: 'https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64'
     gpgkey: 'https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/D42D0685.pub'
     enabled: true
     gpgcheck: true

  #NVIDIA DRIVERS
  #------------
  #- name: install nvidia drivers
    

  
  #INSTALL KDE
  #------------
  - name: install KDE
    dnf:
     name:
      - '@KDE Plasma Workspaces'
      - '@base-x'

  #PROGRAM DEPENDENCIES
  #------------
  - name: general dependencies
    dnf:
     name:
      - bash
      - curl
      - dbus
      - perl
      - git
      - less
      - zsh
      - python3.11
      - htop
      - btop
      - firefox
      - ark
      - flatpak
      - gdb
      - cifs-utils

  - name: install houdini dependencies
    dnf:
     name:
      - alsa-lib
      - cups-libs
      - dbus-libs
      - expat
      - fontconfig
      - glib2
      - glibc
      - libcurl
      - libdrm
      - libgcc
      - libglvnd-egl
      - libglvnd-glx
      - libglvnd-opengl
      - libICE
      - libSM
      - libstdc++
      - libuuid
      - libX11
      - libX11-xcb
      - libxcb
      - libXcomposite
      - libXdamage
      - libXext
      - libXfixes
      - libXi
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbfile
      - libXrandr
      - libXrender
      - libxshmfence
      - libXt
      - libXtst
      - mesa-libGLU
      - ncurses-libs
      - nspr
      - nss
      - nss-util
      - nxagent
      - pciutils-libs
      - xcb-util-cursor
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
      - xcb-util-wm
     state: present
     
  - name: Install Cockpit & Dependencies
    dnf:
     name:
      - cockpit
      - cockpit-storaged
      - cockpit-shell
      - samba-common-tools
      - adcli
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - krb5-workstation
     state: present
  
  - name: Enable Cockpit on launch
    ansible.builtin.service:
     name: cockpit.socket
     enabled: yes
     state: started 
