---
- name: Setup Machines
  hosts: localhost
  connection: local
  become: true
  
  tasks:

  #UPGRADE/INSTALL
  #------------
  - name: Install Nvidia
    yum:
     name:
      - almalinux-release-nvidia-driver
      - nvidia-open-kmod
      - nvidia-driver
      
  - name: Upgrade all packages
    ansible.builtin.yum:
     name: "*"
     state: latest
  
  #INSTALL REPO
  #------------
  - name: Install ELrepo
    yum:
     name: 
      - elrepo-release

  - name: Enable AlmaLinux CRB repo
    community.general.ini_file:
     path:       /etc/yum.repos.d/almalinux-crb.repo
     section:    crb
     option:     enabled
     value:      1
     create:     no
    when: ansible_distribution == "AlmaLinux"

  - name: Enable the RPM Fusion repository
    ansible.builtin.yum:
      name: "{{ item }}"
      state: present
      disable_gpg_check: true
    loop:
       - https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
       - https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
      
  #DOT FILES
  #------------
  - name: setup DNS
    copy:
     src: Files/resolv.conf
     dest: /etc/resolv.conf
     owner: root
     group: root

  #PROGRAM DEPENDENCIES
  #------------
  - name: install houdini dependencies
    yum:
     name:
      - alsa-lib
      - cups-libs
      - dbus-libs
      - expat
      - fontconfig
      - glib2
      - glibc
      - libcurl
      - libdrm
      - libgcc
      - libglvnd-egl
      - libglvnd-glx
      - libglvnd-opengl
      - libICE
      - libSM
      - libstdc++
      - libuuid
      - libX11
      - libX11-xcb
      - libxcb
      - libXcomposite
      - libXdamage
      - libXext
      - libXfixes
      - libXi
      - libxkbcommon
      - libxkbcommon-x11
      - libxkbfile
      - libXrandr
      - libXrender
      - libxshmfence
      - libXt
      - libXtst
      - mesa-libGLU
      - ncurses-libs
      - nspr
      - nss
      - nss-util
      - nxagent
      - pciutils-libs
      - xcb-util-cursor
      - xcb-util-image
      - xcb-util-keysyms
      - xcb-util-renderutil
      - xcb-util-wm
     state: present
     
  - name: Install Cockpit & Dependencies
    yum:
     name:
      - cockpit
      - cockpit-storaged
      - cockpit-shell
      - samba-common-tools
      - adcli
      - sssd
      - realmd
      - oddjob
      - oddjob-mkhomedir
      - krb5-workstation
     state: present
  
  - name: Enable Cockpit on launch
    ansible.builtin.service:
     name: cockpit
     enabled: yes
     state: started
