# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

if [ -f /mnt/aslon/06_Pipeline/configs/alongside_rc.sh ]; then
       source /mnt/aslon/06_Pipeline/configs/alongside_rc.sh
fi

